### ISSUE TITLE
any feedback

### ISSUE THREAD

**Issue by baseio** [eykrehbein/cook#2]
hi,
the way https://github.com/tmrts/boilr prompts for variables is kind of cool,
and its ability to "--copy" from a repo too.

good work!

**Comment by eykrehbein** [comment]
Hey,
first of all, thank you for your feedback!

The features you mentioned are pretty cool! I'll implement them in future version asap.

**Comment by eykrehbein** [comment]
Feature to clone remote boilerplates was added in #4

**Comment by eykrehbein** [comment]
Feature to prompt for variables was added in #6
